name: Deploy to Cloud Run
on:
  push:

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GOOGLE_CREDENTIALS }}"

      - name: Create passwords file
        working-directory: serverpod_cloudrun_server
        shell: bash
        env:
          SERVERPOD_PASSWORDS: ${{ secrets.SERVERPOD_PASSWORDS }}
        run: |
          pwd
          echo "$SERVERPOD_PASSWORDS" > config/passwords.yaml
          ls config/
          
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build the Docker image
        run:  cd serverpod_cloudrun_server && docker build -t server . 

      - name: Push Docker image
        run: docker push server


      - id: deploy
        name: Deploy Docker image
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          image: server
          region: us-central1
          service: app
          flags: --port=8080

      - name: "Use output"
        run: 'curl "${{ steps.deploy.outputs.url }}"'
